import { composerDefaults, composerControls } from "./composer.js";
// Effect recipes are data. Renderer, controls, previews and persistence share this contract.
export const materialDefaults = {
  ...composerDefaults,
  reactionFeed: 0.036,
  reactionKill: 0.061,
  family: "",
  container: 0,
  interior: 0,
  enclosure: 1,
  glassClarity: 0.92,
  glassThickness: 0.14,
  glassTint: 0.25,
  containerWidth: 1,
  containerStretch: 1,
  interiorScale: 0.82,
  interiorDensity: 0.55,
  branchDetail: 5,
  interiorMotion: 0.35,
  emission: 1.5,
  materialScale: 3,
  materialFold: 0.6,
  surfaceActivity: 0.5,
};
export const materialControls = {
  ...composerControls,
  enclosure: [
    "Enclosure",
    0,
    1,
    0.01,
    "How visible the sphere holding a volume is. At zero the bounding shell stops reflecting anything and only the volume inside it is drawn, which is what you want for something that is meant to be a body of light rather than an object in glass.",
    "volumetric bounding shell reflection",
  ],
  containerWidth: [
    "Container width",
    0.5,
    1.5,
    0.01,
    "Changes the horizontal proportions of the enclosure independently of the interior. Try a narrow vial or a wide glass lens.",
    "signed distance nonuniform scale",
  ],
  reactionFeed: [
    "Chemical feed",
    0.02,
    0.07,
    0.001,
    "Replenishes the surface reagent in a persistent feedback simulation. Try 0.036 for branching cells. Allow several seconds after a change.",
    "Gray Scott reaction diffusion feed rate",
  ],
  reactionKill: [
    "Chemical decay",
    0.045,
    0.075,
    0.001,
    "Removes the active reagent. Feed and decay together determine spots, fronts and extinction. Reseed to start the field again.",
    "Gray Scott parameter map",
  ],
  glassClarity: [
    "Clarity",
    0,
    1,
    0.01,
    "How much interior light passes through the shell. Try 0.95 for clear glass or 0.4 for smoked glass. Keep this high to reveal delicate branches.",
    "Beer Lambert glass absorption",
  ],
  glassThickness: [
    "Optical thickness",
    0.02,
    0.5,
    0.01,
    "Controls shell absorption and optical distortion. A small value feels like blown glass; thicker glass bends the interior more strongly.",
    "Snell law glass refraction",
  ],
  glassTint: [
    "Glass tint",
    0,
    1,
    0.01,
    "Tints the glass with your palette. Use a little for champagne edges; high values produce colored laboratory glass.",
    "colored glass absorption spectrum",
  ],
  containerStretch: [
    "Container proportion",
    0.65,
    1.5,
    0.01,
    "Stretches the enclosure vertically. Try a tall specimen vessel or a flattened lens. The interior remains independently scaled.",
    "signed distance ellipsoid",
  ],
  interiorScale: [
    "Interior scale",
    0.2,
    1,
    0.01,
    "How much of the enclosure the structure occupies. Leave space around dendrites for a sense of suspended volume.",
    "negative space volumetric composition",
  ],
  interiorDensity: [
    "Occupancy",
    0.1,
    1,
    0.01,
    "How much of the interior is visible. Low values reveal isolated threads; high values build a dense matrix.",
    "volume rendering density transfer function",
  ],
  branchDetail: [
    "Branch detail",
    2,
    5,
    1,
    "Adds smaller divisions to the internal field. Try 5 for fine branching. High settings need show quality to resolve cleanly.",
    "procedural dendritic branching",
  ],
  interiorMotion: [
    "Internal motion",
    0,
    1.5,
    0.01,
    "Animates the interior independently of camera rotation. Zero holds its structure still while you inspect the glass.",
    "domain warping procedural animation",
  ],
  emission: [
    "Internal radiance",
    0.1,
    4,
    0.05,
    "Brightness of the enclosed material. Small increases preserve detail better than heavy bloom.",
    "emissive volume tone mapping",
  ],
  materialScale: [
    "Structure scale",
    1,
    8,
    0.05,
    "Changes the size of internal folds or surface cells. Smaller values create broad shapes; larger values reveal intricate detail.",
    "domain warped noise shader",
  ],
  materialFold: [
    "Folding",
    0,
    1.5,
    0.01,
    "Bends the material field into overlapping sheets. Try 0.6 for flowing silk and 1.2 for tight folds.",
    "gyroid implicit surface volume rendering",
  ],
  surfaceActivity: [
    "Active coverage",
    0.1,
    0.9,
    0.01,
    "Controls the balance of dark crust and luminous surface. Keep dark regions for contrast.",
    "reaction diffusion Gray Scott patterns",
  ],
};
export const materialSections = {
  orb: [
    [
      "Material structure",
      [
        "materialScale",
        "materialFold",
        "surfaceActivity",
        "interiorMotion",
        "emission",
        "reactionFeed",
        "reactionKill",
      ],
    ],
    [
      "Light & finish",
      ["enclosure", "roughness", "reflection", "bloom", "exposure", "hue"],
    ],
    ["Camera", ["zoom", "tilt", "rotation", "autoRotate"]],
    ["Render quality", ["devScale", "showScale"]],
  ],
};
// Gallery shortcuts: a family selection plus slider values. Every family stays
// choosable from the Shader family dropdown regardless.
export const materialPresets = [
  {
    id: "silk",
    name: "Prismatic silk",
    tag: "IRIDESCENT VOLUME",
    mode: "orb",
    values: {
      family: "silk",
      palette: 4,
      materialFold: 0.65,
      materialScale: 3.2,
      emission: 1.5,
    },
  },
  {
    id: "chrome",
    name: "Liquid mercury",
    tag: "REFLECTIVE SURFACE",
    mode: "orb",
    values: {
      family: "mercury",
      palette: 2,
      materialFold: 0.48,
      materialScale: 2.4,
      roughness: 0.12,
    },
  },
];
export const materialBase = {
  zoom: 1,
  tilt: 0.15,
  autoRotate: 0.08,
  bloom: 0.28,
  exposure: 1.1,
  grain: 0.015,
  vignette: 0.2,
};
